### ISSUE TITLE
協助將新增的水點的note, 即時呈現在地圖上

### ISSUE THREAD

**Issue by amphit** [teia-tw/watermap#1]
使用者在標注水點時, 因為不會直接標注進去OSM底圖, 而是以note形式被紀錄下來. 但是, 使用者會期待直接, 立即看到自己標注的水點呈現在地圖上(成果). 所以, 希望增加這個功能.

**Comment by pm5** [comment]
有了。但我沒有權限關掉 issue。

**Comment by amphit** [comment]
我還在學習github中，先試著關閉他。(不熟悉權限的開設，如果Pm5有需要開權限，再請跟我說。)
